package main

import (
	"github.com/ghargrove/pokemon-web/http/rest"
	"github.com/ghargrove/pokemon-web/internal"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	"log"
)

var schema string = `
CREATE TABLE IF NOT EXISTS users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar);

CREATE TABLE IF NOT EXISTS pokemon (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar);
`

func main() {
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading env file")
	}

	db := internal.CreateDB()
	db.MustExec(schema)

	r := gin.Default()

	r.GET("/sets", rest.HandleAllSets)
	r.GET("/sets/:id", rest.HandleSingleSet)
	r.GET("/sets/:id/cards", rest.HandleCardsForSet)
	r.GET("/users", func(c *gin.Context) {
		rest.HandleAllUsers(c, db)
	})
	r.Run(":8082")
}
